// <auto-generated />
using System;
using CourseBook.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseBook.WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210327111909_MakeFieldNullable")]
    partial class MakeFieldNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.DirectionDisciplineEntity", b =>
                {
                    b.Property<Guid>("DirectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("TEXT");

                    b.HasKey("DirectionId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("directions_disciplines");

                    b.HasData(
                        new
                        {
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            DisciplineId = new Guid("986d7006-65c4-4246-b99a-2d390e1ae4f7")
                        },
                        new
                        {
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            DisciplineId = new Guid("b0a130ae-8d09-4cec-8814-24c811028771")
                        },
                        new
                        {
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            DisciplineId = new Guid("fee99c99-831c-4f29-acd0-5eb5ad0ca7e2")
                        },
                        new
                        {
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            DisciplineId = new Guid("d12b6e66-e758-48ca-af31-102aa991bdc0")
                        },
                        new
                        {
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            DisciplineId = new Guid("0142a5ca-e2ab-423a-a03f-d2c3092a0339")
                        },
                        new
                        {
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            DisciplineId = new Guid("09da399f-d269-4333-b3a9-c7203dee1a01")
                        },
                        new
                        {
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            DisciplineId = new Guid("d4e27800-46bd-48d4-b320-92380548f689")
                        },
                        new
                        {
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            DisciplineId = new Guid("f333c6ac-530c-4092-8160-a336bafb4d6c")
                        },
                        new
                        {
                            DirectionId = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            DisciplineId = new Guid("8e518999-5273-4789-9978-dac4baa4e74c")
                        },
                        new
                        {
                            DirectionId = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            DisciplineId = new Guid("e1de5ca1-58dd-4a15-8544-0b370db9f2bb")
                        },
                        new
                        {
                            DirectionId = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            DisciplineId = new Guid("f5a8d4f5-a85c-4141-be24-7ba4d2bae6ce")
                        },
                        new
                        {
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            DisciplineId = new Guid("1b773c45-0a73-43f9-94d6-af576c52cf9f")
                        },
                        new
                        {
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            DisciplineId = new Guid("5b63a570-f5b2-47e7-8b2f-a79ca090797a")
                        },
                        new
                        {
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            DisciplineId = new Guid("5687210f-0fe3-4111-b0c6-a4764c3ad27c")
                        },
                        new
                        {
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            DisciplineId = new Guid("bc957929-f744-4315-a4ed-08530c7f0f3e")
                        },
                        new
                        {
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            DisciplineId = new Guid("45a4ac18-d257-4bbf-8c90-959c5222aecf")
                        },
                        new
                        {
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            DisciplineId = new Guid("a02c08b7-bd53-43e7-8a83-ead1185fbdd0")
                        },
                        new
                        {
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            DisciplineId = new Guid("db2a6fec-1be3-4e5a-9dc2-71e0104c150d")
                        },
                        new
                        {
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            DisciplineId = new Guid("211181c7-ef7c-4de0-b382-70e0eb9c89d3")
                        },
                        new
                        {
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            DisciplineId = new Guid("d6b13c5b-cabf-4034-af31-f3c30d344393")
                        },
                        new
                        {
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            DisciplineId = new Guid("ad97d079-2037-4dd7-abfd-f23befa01df2")
                        },
                        new
                        {
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            DisciplineId = new Guid("d80697b7-aa62-49e2-86e8-2a83e2e71004")
                        },
                        new
                        {
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            DisciplineId = new Guid("9fe893d9-19e8-4ca5-99a1-09c165918e8b")
                        },
                        new
                        {
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            DisciplineId = new Guid("bc5bc711-5718-4b9c-a6cf-3d08a00f157c")
                        },
                        new
                        {
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            DisciplineId = new Guid("bf026a3f-9e2a-4506-a411-8bda85002c36")
                        },
                        new
                        {
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            DisciplineId = new Guid("4f4ffe1d-b54c-45f7-9e34-a0cc26df4ddd")
                        },
                        new
                        {
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            DisciplineId = new Guid("4bd00c26-498f-439e-b269-5052091dc53f")
                        },
                        new
                        {
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            DisciplineId = new Guid("eeccea9a-ebaa-4660-b2f2-8fad550b38bb")
                        },
                        new
                        {
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            DisciplineId = new Guid("2f9785fd-34f2-47dd-8b5b-e520047213fb")
                        },
                        new
                        {
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            DisciplineId = new Guid("f532bb4b-725b-4b00-8643-a335a4c3fe2f")
                        },
                        new
                        {
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            DisciplineId = new Guid("96e8af39-7453-49cb-af5a-28d1e64e001a")
                        },
                        new
                        {
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            DisciplineId = new Guid("0af79477-a80e-4eb6-b156-97bc4cb47315")
                        },
                        new
                        {
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            DisciplineId = new Guid("a5f99e5d-a6a6-4a15-96b0-b2c3f54ce06c")
                        },
                        new
                        {
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            DisciplineId = new Guid("1faf9ce2-d392-4097-af23-2d962b90e9d6")
                        },
                        new
                        {
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            DisciplineId = new Guid("ac542825-f958-4103-91ec-89e6363f0d43")
                        },
                        new
                        {
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            DisciplineId = new Guid("7131c3a2-4bc4-4195-859a-f5af9bd7d144")
                        },
                        new
                        {
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            DisciplineId = new Guid("9f160c04-c98b-4d58-a631-cdec4a04e316")
                        },
                        new
                        {
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            DisciplineId = new Guid("fef757f5-8653-4ac3-814d-b60af590ce5a")
                        },
                        new
                        {
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            DisciplineId = new Guid("075486bf-0147-4bf7-97ca-e83191675bfb")
                        },
                        new
                        {
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            DisciplineId = new Guid("96cd27bd-dcff-496b-9984-4489b11a2712")
                        },
                        new
                        {
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            DisciplineId = new Guid("b46cc5bc-6fc4-4f1e-9b2a-ff68b3f1234d")
                        },
                        new
                        {
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            DisciplineId = new Guid("3ac05f7b-8ee9-4bf5-a37b-692eb9670c35")
                        },
                        new
                        {
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            DisciplineId = new Guid("aad3f967-7158-46ca-9b8a-405581f207a4")
                        },
                        new
                        {
                            DirectionId = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            DisciplineId = new Guid("e55051fc-17a6-41ec-b76e-fe6d98a15058")
                        },
                        new
                        {
                            DirectionId = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            DisciplineId = new Guid("65830d5c-c0b3-46b6-8bea-b3dd2ce6e1dd")
                        },
                        new
                        {
                            DirectionId = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            DisciplineId = new Guid("54f742d3-a89d-4e4a-bd39-d233e0c34395")
                        },
                        new
                        {
                            DirectionId = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            DisciplineId = new Guid("27bedee0-3b3e-4ab2-9bab-7f910ea12df2")
                        },
                        new
                        {
                            DirectionId = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            DisciplineId = new Guid("f3a05565-4293-47b4-8799-78a7e0d8787f")
                        },
                        new
                        {
                            DirectionId = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            DisciplineId = new Guid("abc7d661-c1c4-4bd7-b767-d88ce7b748e5")
                        },
                        new
                        {
                            DirectionId = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            DisciplineId = new Guid("7798ec77-2078-410b-9a47-3ecb1f17b100")
                        },
                        new
                        {
                            DirectionId = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            DisciplineId = new Guid("5f926e12-86e0-4c9f-9f99-734ef39575ca")
                        },
                        new
                        {
                            DirectionId = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            DisciplineId = new Guid("0a89c092-a7df-4570-b7a4-1042d4a08b04")
                        },
                        new
                        {
                            DirectionId = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            DisciplineId = new Guid("579e5d9d-cf33-41d4-a172-56853419f169")
                        },
                        new
                        {
                            DirectionId = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            DisciplineId = new Guid("c43c64b6-d37d-44b6-a6cc-ad890e942b1b")
                        },
                        new
                        {
                            DirectionId = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            DisciplineId = new Guid("ff28aa68-df77-4829-a2ce-f322d4b15a2b")
                        });
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.DirectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("directions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            FacultyId = new Guid("6b3957c3-d16e-4620-8d2c-b26239a7a2a8"),
                            Name = "Culturology"
                        },
                        new
                        {
                            Id = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            FacultyId = new Guid("6b3957c3-d16e-4620-8d2c-b26239a7a2a8"),
                            Name = "Pedagogy"
                        },
                        new
                        {
                            Id = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            FacultyId = new Guid("6b3957c3-d16e-4620-8d2c-b26239a7a2a8"),
                            Name = "Design"
                        },
                        new
                        {
                            Id = new Guid("fa2a6596-0f78-42c8-8f3f-56430aa50087"),
                            FacultyId = new Guid("6b3957c3-d16e-4620-8d2c-b26239a7a2a8"),
                            Name = "Library and Information Activities"
                        },
                        new
                        {
                            Id = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            FacultyId = new Guid("e05d5966-b197-4bd1-92d4-800f66b352fe"),
                            Name = "Astronomy and Space Geodesy"
                        },
                        new
                        {
                            Id = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            FacultyId = new Guid("e05d5966-b197-4bd1-92d4-800f66b352fe"),
                            Name = "Quantum Field Theory"
                        },
                        new
                        {
                            Id = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            FacultyId = new Guid("e05d5966-b197-4bd1-92d4-800f66b352fe"),
                            Name = "General and Experimental Physics"
                        },
                        new
                        {
                            Id = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            FacultyId = new Guid("e05d5966-b197-4bd1-92d4-800f66b352fe"),
                            Name = "Optics and Spectroscopy"
                        },
                        new
                        {
                            Id = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            FacultyId = new Guid("b0d09040-c5ea-492d-936f-488b9f3115a2"),
                            Name = "Radiophysics"
                        },
                        new
                        {
                            Id = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            FacultyId = new Guid("b0d09040-c5ea-492d-936f-488b9f3115a2"),
                            Name = "Radio electronics"
                        },
                        new
                        {
                            Id = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            FacultyId = new Guid("b0d09040-c5ea-492d-936f-488b9f3115a2"),
                            Name = "Semiconductor Electronics"
                        },
                        new
                        {
                            Id = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            FacultyId = new Guid("b0d09040-c5ea-492d-936f-488b9f3115a2"),
                            Name = "Optoelectronic systems and remote sensing"
                        },
                        new
                        {
                            Id = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            FacultyId = new Guid("4a823069-9673-403c-8ea0-59b225e5491c"),
                            Name = "Analytical Chemistry"
                        },
                        new
                        {
                            Id = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            FacultyId = new Guid("4a823069-9673-403c-8ea0-59b225e5491c"),
                            Name = "Macromolecular compounds"
                        },
                        new
                        {
                            Id = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            FacultyId = new Guid("4a823069-9673-403c-8ea0-59b225e5491c"),
                            Name = "Petrochemistry"
                        },
                        new
                        {
                            Id = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            FacultyId = new Guid("4a823069-9673-403c-8ea0-59b225e5491c"),
                            Name = "Physical chemistry"
                        });
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.DisciplineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Literatures")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("disciplines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("986d7006-65c4-4246-b99a-2d390e1ae4f7"),
                            Name = "Art history"
                        },
                        new
                        {
                            Id = new Guid("b0a130ae-8d09-4cec-8814-24c811028771"),
                            Name = "Composition"
                        },
                        new
                        {
                            Id = new Guid("fee99c99-831c-4f29-acd0-5eb5ad0ca7e2"),
                            Name = "Sociology of media"
                        },
                        new
                        {
                            Id = new Guid("d12b6e66-e758-48ca-af31-102aa991bdc0"),
                            Name = "History of material culture"
                        },
                        new
                        {
                            Id = new Guid("0142a5ca-e2ab-423a-a03f-d2c3092a0339"),
                            Name = "Information law"
                        },
                        new
                        {
                            Id = new Guid("09da399f-d269-4333-b3a9-c7203dee1a01"),
                            Name = "Copyright"
                        },
                        new
                        {
                            Id = new Guid("d4e27800-46bd-48d4-b320-92380548f689"),
                            Name = "Quantitative methods in scientific research"
                        },
                        new
                        {
                            Id = new Guid("f333c6ac-530c-4092-8160-a336bafb4d6c"),
                            Name = "Strategic management in the library"
                        },
                        new
                        {
                            Id = new Guid("8e518999-5273-4789-9978-dac4baa4e74c"),
                            Name = "Foreign language"
                        },
                        new
                        {
                            Id = new Guid("e1de5ca1-58dd-4a15-8544-0b370db9f2bb"),
                            Name = "Academic writing"
                        },
                        new
                        {
                            Id = new Guid("f5a8d4f5-a85c-4141-be24-7ba4d2bae6ce"),
                            Name = "Museology, conservation and restoration of historical and cultural objects"
                        },
                        new
                        {
                            Id = new Guid("1b773c45-0a73-43f9-94d6-af576c52cf9f"),
                            Name = "Modern problems of physics of the microworld and cosmology"
                        },
                        new
                        {
                            Id = new Guid("5b63a570-f5b2-47e7-8b2f-a79ca090797a"),
                            Name = "Foreign language in the field of professional communication"
                        },
                        new
                        {
                            Id = new Guid("5687210f-0fe3-4111-b0c6-a4764c3ad27c"),
                            Name = "Waves and layers in plasma"
                        },
                        new
                        {
                            Id = new Guid("bc957929-f744-4315-a4ed-08530c7f0f3e"),
                            Name = "Plasma physics problems"
                        },
                        new
                        {
                            Id = new Guid("45a4ac18-d257-4bbf-8c90-959c5222aecf"),
                            Name = "Military training"
                        },
                        new
                        {
                            Id = new Guid("a02c08b7-bd53-43e7-8a83-ead1185fbdd0"),
                            Name = "Information systems design"
                        },
                        new
                        {
                            Id = new Guid("db2a6fec-1be3-4e5a-9dc2-71e0104c150d"),
                            Name = "Laboratories specializing in satellite dynamics"
                        },
                        new
                        {
                            Id = new Guid("211181c7-ef7c-4de0-b382-70e0eb9c89d3"),
                            Name = "Global Positioning Technologies"
                        },
                        new
                        {
                            Id = new Guid("d6b13c5b-cabf-4034-af31-f3c30d344393"),
                            Name = "Modern problems of physics of the microworld and cosmology"
                        },
                        new
                        {
                            Id = new Guid("ad97d079-2037-4dd7-abfd-f23befa01df2"),
                            Name = "Physics of intermolecular interactions"
                        },
                        new
                        {
                            Id = new Guid("d80697b7-aa62-49e2-86e8-2a83e2e71004"),
                            Name = "The theory of elementary particles"
                        },
                        new
                        {
                            Id = new Guid("9fe893d9-19e8-4ca5-99a1-09c165918e8b"),
                            Name = "Topical issues of theory and teaching methods in physics"
                        },
                        new
                        {
                            Id = new Guid("bc5bc711-5718-4b9c-a6cf-3d08a00f157c"),
                            Name = "Fundamentals of Atomic and Molecular Spectroscopy"
                        },
                        new
                        {
                            Id = new Guid("bf026a3f-9e2a-4506-a411-8bda85002c36"),
                            Name = "Foreign language in the field of professional communication"
                        },
                        new
                        {
                            Id = new Guid("4f4ffe1d-b54c-45f7-9e34-a0cc26df4ddd"),
                            Name = "Analysis of complex biophysical signals"
                        },
                        new
                        {
                            Id = new Guid("4bd00c26-498f-439e-b269-5052091dc53f"),
                            Name = "Biomedical laser technology"
                        },
                        new
                        {
                            Id = new Guid("eeccea9a-ebaa-4660-b2f2-8fad550b38bb"),
                            Name = "Linear Algebra"
                        },
                        new
                        {
                            Id = new Guid("2f9785fd-34f2-47dd-8b5b-e520047213fb"),
                            Name = "Physics"
                        },
                        new
                        {
                            Id = new Guid("f532bb4b-725b-4b00-8643-a335a4c3fe2f"),
                            Name = "Mathematical analysis"
                        },
                        new
                        {
                            Id = new Guid("96e8af39-7453-49cb-af5a-28d1e64e001a"),
                            Name = "Foreign language"
                        },
                        new
                        {
                            Id = new Guid("0af79477-a80e-4eb6-b156-97bc4cb47315"),
                            Name = "Microprocessors"
                        },
                        new
                        {
                            Id = new Guid("a5f99e5d-a6a6-4a15-96b0-b2c3f54ce06c"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("1faf9ce2-d392-4097-af23-2d962b90e9d6"),
                            Name = "Optics Basics"
                        },
                        new
                        {
                            Id = new Guid("ac542825-f958-4103-91ec-89e6363f0d43"),
                            Name = "Military training"
                        },
                        new
                        {
                            Id = new Guid("7131c3a2-4bc4-4195-859a-f5af9bd7d144"),
                            Name = "	Mobile communication systems"
                        },
                        new
                        {
                            Id = new Guid("9f160c04-c98b-4d58-a631-cdec4a04e316"),
                            Name = "Metrology"
                        },
                        new
                        {
                            Id = new Guid("fef757f5-8653-4ac3-814d-b60af590ce5a"),
                            Name = "Digital spectral analysis of signals and fields"
                        },
                        new
                        {
                            Id = new Guid("075486bf-0147-4bf7-97ca-e83191675bfb"),
                            Name = "	Standardization and certification"
                        },
                        new
                        {
                            Id = new Guid("96cd27bd-dcff-496b-9984-4489b11a2712"),
                            Name = "Waveguide Photonics"
                        },
                        new
                        {
                            Id = new Guid("b46cc5bc-6fc4-4f1e-9b2a-ff68b3f1234d"),
                            Name = "Atomic and Nuclear Physics"
                        },
                        new
                        {
                            Id = new Guid("3ac05f7b-8ee9-4bf5-a37b-692eb9670c35"),
                            Name = "Elective disciplines in physical culture and sports"
                        },
                        new
                        {
                            Id = new Guid("aad3f967-7158-46ca-9b8a-405581f207a4"),
                            Name = "Study Practice"
                        },
                        new
                        {
                            Id = new Guid("e55051fc-17a6-41ec-b76e-fe6d98a15058"),
                            Name = "Analytical chemistry"
                        },
                        new
                        {
                            Id = new Guid("65830d5c-c0b3-46b6-8bea-b3dd2ce6e1dd"),
                            Name = "Foreign language"
                        },
                        new
                        {
                            Id = new Guid("54f742d3-a89d-4e4a-bd39-d233e0c34395"),
                            Name = "Quantum chemistry"
                        },
                        new
                        {
                            Id = new Guid("27bedee0-3b3e-4ab2-9bab-7f910ea12df2"),
                            Name = "Pedagogy"
                        },
                        new
                        {
                            Id = new Guid("f3a05565-4293-47b4-8799-78a7e0d8787f"),
                            Name = "Polymer solutions"
                        },
                        new
                        {
                            Id = new Guid("abc7d661-c1c4-4bd7-b767-d88ce7b748e5"),
                            Name = "Chemical modification of polymers"
                        },
                        new
                        {
                            Id = new Guid("7798ec77-2078-410b-9a47-3ecb1f17b100"),
                            Name = "Chemical foundations of biological processes"
                        },
                        new
                        {
                            Id = new Guid("5f926e12-86e0-4c9f-9f99-734ef39575ca"),
                            Name = "Polymer synthesis methods"
                        },
                        new
                        {
                            Id = new Guid("0a89c092-a7df-4570-b7a4-1042d4a08b04"),
                            Name = "Analysis of the quality of hydrocarbon raw materials and products of its processing"
                        },
                        new
                        {
                            Id = new Guid("579e5d9d-cf33-41d4-a172-56853419f169"),
                            Name = "Theoretical foundations of oil refining"
                        },
                        new
                        {
                            Id = new Guid("c43c64b6-d37d-44b6-a6cc-ad890e942b1b"),
                            Name = "Methods for the transmission of scientific information"
                        },
                        new
                        {
                            Id = new Guid("ff28aa68-df77-4829-a2ce-f322d4b15a2b"),
                            Name = "Theoretical foundations of oil refining"
                        });
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.FacultyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("faculties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b3957c3-d16e-4620-8d2c-b26239a7a2a8"),
                            Name = "Institute of Arts and Culture"
                        },
                        new
                        {
                            Id = new Guid("e05d5966-b197-4bd1-92d4-800f66b352fe"),
                            Name = "Faculty of Physics"
                        },
                        new
                        {
                            Id = new Guid("b0d09040-c5ea-492d-936f-488b9f3115a2"),
                            Name = "Faculty of Radiophysics"
                        },
                        new
                        {
                            Id = new Guid("4a823069-9673-403c-8ea0-59b225e5491c"),
                            Name = "Faculty of Chemistry"
                        });
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.GroupDisciplineEntity", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeacherId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("TeacherId");

                    b.ToTable("groups_disciplines");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.GroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DirectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.ToTable("groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbf4d1b7-5dd6-4737-b78c-e865cbe4adc0"),
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            Name = "931910"
                        },
                        new
                        {
                            Id = new Guid("bfd64d63-203b-47f1-86c4-c483b6cb48ac"),
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            Name = "932010"
                        },
                        new
                        {
                            Id = new Guid("c06d5b88-917b-42ad-a032-224cf2cbb34b"),
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            Name = "932028"
                        },
                        new
                        {
                            Id = new Guid("995fefec-b444-4755-9e70-bee240d47c9e"),
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            Name = "931928"
                        },
                        new
                        {
                            Id = new Guid("b719e956-a46c-41b5-93bd-81bd4e12c7ed"),
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            Name = "93180"
                        },
                        new
                        {
                            Id = new Guid("d85b1c42-f9b2-4fbb-bc35-1e93c4f311be"),
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            Name = "931802"
                        },
                        new
                        {
                            Id = new Guid("11f1a4ae-64ef-4708-945f-001ec13475cb"),
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            Name = "931804"
                        },
                        new
                        {
                            Id = new Guid("150043db-fafd-47af-a367-1865429a3b06"),
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            Name = "931803"
                        },
                        new
                        {
                            Id = new Guid("6b5539c4-5008-489f-bee7-d10063412727"),
                            DirectionId = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            Name = "93190"
                        },
                        new
                        {
                            Id = new Guid("4779771c-16be-49ad-af93-d2c3af799ffa"),
                            DirectionId = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            Name = "931901"
                        },
                        new
                        {
                            Id = new Guid("c894f7d5-102f-454c-87c9-ff00086f43c4"),
                            DirectionId = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            Name = "931902"
                        },
                        new
                        {
                            Id = new Guid("e55a88ef-d73f-40f6-941a-6ebd51d0df33"),
                            DirectionId = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            Name = "931903"
                        },
                        new
                        {
                            Id = new Guid("99cee655-2eb3-49a1-8b7b-98f5cdf27dc0"),
                            DirectionId = new Guid("fa2a6596-0f78-42c8-8f3f-56430aa50087"),
                            Name = "93200"
                        },
                        new
                        {
                            Id = new Guid("f18a4b0e-bf34-4038-aa35-961ee944fc62"),
                            DirectionId = new Guid("fa2a6596-0f78-42c8-8f3f-56430aa50087"),
                            Name = "93201"
                        },
                        new
                        {
                            Id = new Guid("1d31e987-c3b7-4e79-8aa8-61482da3987e"),
                            DirectionId = new Guid("fa2a6596-0f78-42c8-8f3f-56430aa50087"),
                            Name = "93202"
                        },
                        new
                        {
                            Id = new Guid("65ca36aa-54f8-4384-af13-f16779251686"),
                            DirectionId = new Guid("fa2a6596-0f78-42c8-8f3f-56430aa50087"),
                            Name = "93203"
                        },
                        new
                        {
                            Id = new Guid("2e596386-82f0-422c-a0d1-6c9325b2b8c5"),
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            Name = "122001"
                        },
                        new
                        {
                            Id = new Guid("177aca2d-65d7-4d69-88bf-95488732d0c5"),
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            Name = "122002"
                        },
                        new
                        {
                            Id = new Guid("97d0822d-49aa-47df-b483-6f9d8ee29804"),
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            Name = "122003"
                        },
                        new
                        {
                            Id = new Guid("9ae4c644-778d-4358-90cf-7fdd895018c5"),
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            Name = "122004"
                        },
                        new
                        {
                            Id = new Guid("de67b121-67e1-4daf-afce-cd7f5fcd73f0"),
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            Name = "121901"
                        },
                        new
                        {
                            Id = new Guid("0ea53180-ed44-4898-a892-c40077d05e65"),
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            Name = "121902"
                        },
                        new
                        {
                            Id = new Guid("2bc26348-3840-4d75-b5b8-307b5664d9d8"),
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            Name = "121903"
                        },
                        new
                        {
                            Id = new Guid("3898a741-3487-4cff-bb0c-833730a7bfb5"),
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            Name = "121904"
                        },
                        new
                        {
                            Id = new Guid("375f4cd0-0dfe-4549-a250-b038a30badd5"),
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            Name = "24200"
                        },
                        new
                        {
                            Id = new Guid("3a8fecd3-ef58-4894-a716-851ba1955172"),
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            Name = "24201"
                        },
                        new
                        {
                            Id = new Guid("55d59cff-8589-454f-92d3-bfc3862567fc"),
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            Name = "24202"
                        },
                        new
                        {
                            Id = new Guid("c0ef4a72-dac8-4ea8-a9b5-78f8865e9ad9"),
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            Name = "24203"
                        },
                        new
                        {
                            Id = new Guid("89767b3d-6327-4125-97c4-b9a2b84854b8"),
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            Name = "24301"
                        },
                        new
                        {
                            Id = new Guid("b6ac4a85-9cfb-426e-9b0c-1bea922f4567"),
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            Name = "24302"
                        },
                        new
                        {
                            Id = new Guid("f2d957fa-c1fd-47a4-b0c0-f316dbeda20f"),
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            Name = "24303"
                        },
                        new
                        {
                            Id = new Guid("adb7bc56-69ad-401a-9f98-ca7237712022"),
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            Name = "24304"
                        },
                        new
                        {
                            Id = new Guid("63f903de-5162-45f1-90fe-68e1b1375431"),
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            Name = "25301"
                        },
                        new
                        {
                            Id = new Guid("1d667208-71cd-4ffc-8edf-ce6b71121da8"),
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            Name = "25302"
                        },
                        new
                        {
                            Id = new Guid("085e3eb8-a9d8-4b04-ac37-3b3c8e417330"),
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            Name = "25303"
                        },
                        new
                        {
                            Id = new Guid("0aece601-4a7e-4b22-809f-c7a3f560e7ae"),
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            Name = "25304"
                        },
                        new
                        {
                            Id = new Guid("ef31ca1b-8b5c-497f-b4a6-c9c602ce3e17"),
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            Name = "30001"
                        },
                        new
                        {
                            Id = new Guid("bc28bb75-ec40-4118-a652-4dfda2189c42"),
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            Name = "30002"
                        },
                        new
                        {
                            Id = new Guid("97f0b426-f8bd-496c-b8af-7b5432c35eca"),
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            Name = "30003"
                        },
                        new
                        {
                            Id = new Guid("baa44940-e055-4097-9d35-23ff36c24ece"),
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            Name = "30004"
                        },
                        new
                        {
                            Id = new Guid("bc6f600e-3c90-4fd2-a650-7fe8496d6b99"),
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            Name = "40001"
                        },
                        new
                        {
                            Id = new Guid("d47f6ceb-be52-4d14-94c2-3891dae8524d"),
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            Name = "40002"
                        },
                        new
                        {
                            Id = new Guid("8d22e5be-874c-4467-a8a6-10ec4be05940"),
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            Name = "40003"
                        },
                        new
                        {
                            Id = new Guid("f12316e7-00a1-44d1-8cd4-f130cb1549d7"),
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            Name = "40004"
                        },
                        new
                        {
                            Id = new Guid("301db25d-27bc-4fdd-9422-76161b433222"),
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            Name = "50001"
                        },
                        new
                        {
                            Id = new Guid("61779bbf-e712-4c4f-9c1c-cfde792f8123"),
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            Name = "50002"
                        },
                        new
                        {
                            Id = new Guid("6600b84a-46d6-4457-b553-2bc76cf429b1"),
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            Name = "50003"
                        },
                        new
                        {
                            Id = new Guid("21e70871-00c4-435f-a58f-e5ee217c9daf"),
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            Name = "50004"
                        },
                        new
                        {
                            Id = new Guid("53b46c40-973d-4011-96bd-88b6d6d2f266"),
                            DirectionId = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            Name = "60001"
                        },
                        new
                        {
                            Id = new Guid("0c9e1c5b-b73c-4761-9e8b-3fac8fe1ec39"),
                            DirectionId = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            Name = "60002"
                        },
                        new
                        {
                            Id = new Guid("0d4c5368-15a1-46a4-9605-723c91d725bc"),
                            DirectionId = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            Name = "60003"
                        },
                        new
                        {
                            Id = new Guid("d6382f9d-4e4c-45b3-8b34-4a63e69de09f"),
                            DirectionId = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            Name = "60004"
                        },
                        new
                        {
                            Id = new Guid("deff19d1-bf42-4d14-9ac1-5c21b2a18a5c"),
                            DirectionId = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            Name = "70001"
                        },
                        new
                        {
                            Id = new Guid("e9880029-92c6-4143-a680-00c06e6347d3"),
                            DirectionId = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            Name = "70002"
                        },
                        new
                        {
                            Id = new Guid("0d80b63a-50d1-4c0f-b1f7-0a351d57192e"),
                            DirectionId = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            Name = "70003"
                        },
                        new
                        {
                            Id = new Guid("0ccaf237-249b-49a2-91bf-4e13199f0ed8"),
                            DirectionId = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            Name = "70004"
                        },
                        new
                        {
                            Id = new Guid("78b0c8a8-02d4-476d-a201-667cd79d0557"),
                            DirectionId = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            Name = "80001"
                        },
                        new
                        {
                            Id = new Guid("a06269e9-85a7-4108-b199-0a5f81b9dedd"),
                            DirectionId = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            Name = "80002"
                        },
                        new
                        {
                            Id = new Guid("4320ca86-9aaf-42fb-8832-35c9076e5b05"),
                            DirectionId = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            Name = "80003"
                        },
                        new
                        {
                            Id = new Guid("462afa34-c206-4761-bd96-b87e72d1d243"),
                            DirectionId = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            Name = "80004"
                        },
                        new
                        {
                            Id = new Guid("7e311ede-5d6c-4df4-9c64-192e00f65cf9"),
                            DirectionId = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            Name = "90001"
                        },
                        new
                        {
                            Id = new Guid("24b4ee8d-c599-41b2-be5c-b27597cf278b"),
                            DirectionId = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            Name = "90002"
                        },
                        new
                        {
                            Id = new Guid("deea0a5c-fb24-4994-9384-fabe85e4a76a"),
                            DirectionId = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            Name = "90003"
                        },
                        new
                        {
                            Id = new Guid("4af28876-24b2-4f33-ac7b-4c4c95385ab3"),
                            DirectionId = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            Name = "90004"
                        },
                        new
                        {
                            Id = new Guid("26441b22-1be9-432f-a06a-ebc9e4222f6e"),
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            Name = "931910"
                        },
                        new
                        {
                            Id = new Guid("c4ba2c3f-6f86-41a2-b79e-0288e25b5d06"),
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            Name = "932010"
                        },
                        new
                        {
                            Id = new Guid("dc0a6e03-06ab-4f32-8714-841367f13739"),
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            Name = "932028"
                        },
                        new
                        {
                            Id = new Guid("590eb367-5fcf-4b67-a350-e2f87a688ef4"),
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            Name = "931928"
                        },
                        new
                        {
                            Id = new Guid("69626a13-91ce-4281-bb74-2dac4c1a6db8"),
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            Name = "93180"
                        },
                        new
                        {
                            Id = new Guid("ee357e08-2b26-4e71-97cc-a4a9aeb7b94e"),
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            Name = "931802"
                        },
                        new
                        {
                            Id = new Guid("d37caba8-8a5e-43f5-bdf7-96f8d4ee437c"),
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            Name = "931804"
                        },
                        new
                        {
                            Id = new Guid("e90ec78b-115f-4d45-af21-1f6e89b3ea62"),
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            Name = "931803"
                        },
                        new
                        {
                            Id = new Guid("a1c8530c-7aca-463b-a2cb-4c18c72957ec"),
                            DirectionId = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            Name = "93190"
                        },
                        new
                        {
                            Id = new Guid("43559fcb-8bae-4cc0-9576-f2835a3061f9"),
                            DirectionId = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            Name = "931901"
                        },
                        new
                        {
                            Id = new Guid("ae932456-b33f-486a-93dc-adb27c290296"),
                            DirectionId = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            Name = "931902"
                        },
                        new
                        {
                            Id = new Guid("43017bdf-3026-4607-a266-30948c613f0d"),
                            DirectionId = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            Name = "931903"
                        },
                        new
                        {
                            Id = new Guid("8ce7c591-597d-4e4a-9702-78410cc91fbe"),
                            DirectionId = new Guid("fa2a6596-0f78-42c8-8f3f-56430aa50087"),
                            Name = "93200"
                        },
                        new
                        {
                            Id = new Guid("3b541a3e-1e89-48e0-8283-d46fe573bab0"),
                            DirectionId = new Guid("fa2a6596-0f78-42c8-8f3f-56430aa50087"),
                            Name = "93201"
                        },
                        new
                        {
                            Id = new Guid("6fec86e7-be04-4daf-889a-8fb9e048f935"),
                            DirectionId = new Guid("fa2a6596-0f78-42c8-8f3f-56430aa50087"),
                            Name = "93202"
                        },
                        new
                        {
                            Id = new Guid("569b3af3-11b3-4c14-a365-3444136317c9"),
                            DirectionId = new Guid("fa2a6596-0f78-42c8-8f3f-56430aa50087"),
                            Name = "93203"
                        },
                        new
                        {
                            Id = new Guid("4e9a677c-03a0-4a67-b0fd-6c23560297be"),
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            Name = "122001"
                        },
                        new
                        {
                            Id = new Guid("fb9fb634-5a7a-4975-93c5-13c47e2d7a88"),
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            Name = "122002"
                        },
                        new
                        {
                            Id = new Guid("a17b86b9-9e59-47be-b497-ac7e681a6490"),
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            Name = "122003"
                        },
                        new
                        {
                            Id = new Guid("714b27cd-c133-459c-91ea-d4be6879f6df"),
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            Name = "122004"
                        },
                        new
                        {
                            Id = new Guid("be0b569f-4f07-4b32-98d6-90580e55f4bd"),
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            Name = "121901"
                        },
                        new
                        {
                            Id = new Guid("d37e2391-3b24-4258-8543-25cb3e8e6021"),
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            Name = "121902"
                        },
                        new
                        {
                            Id = new Guid("7f21c712-e107-4dc5-8bcc-8c8d3e29611b"),
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            Name = "121903"
                        },
                        new
                        {
                            Id = new Guid("7b328e66-8d7f-4677-adf6-32d296aef412"),
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            Name = "121904"
                        },
                        new
                        {
                            Id = new Guid("a2df678d-7461-4453-be7f-b854eb2eb0b1"),
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            Name = "24200"
                        },
                        new
                        {
                            Id = new Guid("6e2c0941-ecf1-4f9c-a2fc-71b498926a25"),
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            Name = "24201"
                        },
                        new
                        {
                            Id = new Guid("adcfeb4f-e104-4619-ab33-13bdb9603d6a"),
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            Name = "24202"
                        },
                        new
                        {
                            Id = new Guid("49de0fc1-fd7a-4f99-82c1-2bdc4051d6c6"),
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            Name = "24203"
                        },
                        new
                        {
                            Id = new Guid("6e6f8434-5155-41bc-9186-01e9a4ea2c2e"),
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            Name = "24301"
                        },
                        new
                        {
                            Id = new Guid("ab5461c6-6b82-4ec0-b106-7c649c30aa4e"),
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            Name = "24302"
                        },
                        new
                        {
                            Id = new Guid("f5a97d11-9036-4a51-ac76-44ff3cccdced"),
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            Name = "24303"
                        },
                        new
                        {
                            Id = new Guid("796b3f0f-15aa-4a44-83d1-eb0d004e6ba9"),
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            Name = "24304"
                        },
                        new
                        {
                            Id = new Guid("63904fb7-50a7-4d97-a012-82cb80e8bf1e"),
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            Name = "25301"
                        },
                        new
                        {
                            Id = new Guid("04422cad-54f1-48d7-ae30-f5bfefb085fa"),
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            Name = "25302"
                        },
                        new
                        {
                            Id = new Guid("16b4c772-5ef3-48d6-9380-ca6b371a0a29"),
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            Name = "25303"
                        },
                        new
                        {
                            Id = new Guid("bbcd32b0-eee0-4528-9a98-2bd190050b1a"),
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            Name = "25304"
                        },
                        new
                        {
                            Id = new Guid("954ada8e-3081-4c7a-8cb9-6486ca9c0c78"),
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            Name = "30001"
                        },
                        new
                        {
                            Id = new Guid("70f6eee6-cc82-4b56-8e36-f0855858cc25"),
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            Name = "30002"
                        },
                        new
                        {
                            Id = new Guid("7b9a7b18-b25f-43dd-be9b-6b11cb6a629b"),
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            Name = "30003"
                        },
                        new
                        {
                            Id = new Guid("c6f70945-fc4e-4637-a90f-ad9a859c0b3a"),
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            Name = "30004"
                        },
                        new
                        {
                            Id = new Guid("9f02f059-f663-4c89-a803-30c0913c6095"),
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            Name = "40001"
                        },
                        new
                        {
                            Id = new Guid("a7d2019d-db79-4e4e-9142-4fd7e5595210"),
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            Name = "40002"
                        },
                        new
                        {
                            Id = new Guid("92560e1e-10b6-4e22-a3c7-4b44b57a4c2d"),
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            Name = "40003"
                        },
                        new
                        {
                            Id = new Guid("d054363e-9ac6-471c-927a-44ede49e14b9"),
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            Name = "40004"
                        },
                        new
                        {
                            Id = new Guid("66bfc87e-0176-48b8-86f7-d6bb27145544"),
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            Name = "50001"
                        },
                        new
                        {
                            Id = new Guid("80e4da28-2726-484b-98d3-acf2f685f110"),
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            Name = "50002"
                        },
                        new
                        {
                            Id = new Guid("d76d264f-afb3-43e8-ba47-78a12d6630e7"),
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            Name = "50003"
                        },
                        new
                        {
                            Id = new Guid("fa09fced-f0ec-4f86-8635-548169c085d2"),
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            Name = "50004"
                        },
                        new
                        {
                            Id = new Guid("9b28da7a-9b71-4f57-a682-977f6a6592ab"),
                            DirectionId = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            Name = "60001"
                        },
                        new
                        {
                            Id = new Guid("10ea97d6-aebe-4ef3-bc5a-0d3410762d17"),
                            DirectionId = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            Name = "60002"
                        },
                        new
                        {
                            Id = new Guid("a0c045de-a8a9-4261-b3f6-6f933ea0a2f3"),
                            DirectionId = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            Name = "60003"
                        },
                        new
                        {
                            Id = new Guid("70eccf2a-b381-413e-b58e-c1850d09d638"),
                            DirectionId = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            Name = "60004"
                        },
                        new
                        {
                            Id = new Guid("cbd62f90-c44d-47e1-a049-ae1d5b94e3e7"),
                            DirectionId = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            Name = "70001"
                        },
                        new
                        {
                            Id = new Guid("eeb1dd57-104c-40ca-b6ea-e64ecfdc55d4"),
                            DirectionId = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            Name = "70002"
                        },
                        new
                        {
                            Id = new Guid("41178a4d-8d1d-49e4-a0ee-80965e1df5ab"),
                            DirectionId = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            Name = "70003"
                        },
                        new
                        {
                            Id = new Guid("eb781120-10cf-4161-a235-726b23c3a6c6"),
                            DirectionId = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            Name = "70004"
                        },
                        new
                        {
                            Id = new Guid("b129f3e3-a379-45a3-953c-ce69bcf097d5"),
                            DirectionId = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            Name = "80001"
                        },
                        new
                        {
                            Id = new Guid("ae0242e1-8c6e-4e6d-99a5-2f55b6e44a47"),
                            DirectionId = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            Name = "80002"
                        },
                        new
                        {
                            Id = new Guid("0b7978c5-8e25-45a4-902c-9f6ff5d53b87"),
                            DirectionId = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            Name = "80003"
                        },
                        new
                        {
                            Id = new Guid("04172373-df80-4d60-90df-a4efa8e74941"),
                            DirectionId = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            Name = "80004"
                        },
                        new
                        {
                            Id = new Guid("6d4c1ffe-3caa-472c-82e7-040fa3081142"),
                            DirectionId = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            Name = "90001"
                        },
                        new
                        {
                            Id = new Guid("85b6e537-c106-41df-9ec4-5bc8e3b9be17"),
                            DirectionId = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            Name = "90002"
                        },
                        new
                        {
                            Id = new Guid("500c28c8-fcb8-4f56-9e35-4956e579e63d"),
                            DirectionId = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            Name = "90003"
                        },
                        new
                        {
                            Id = new Guid("b8810aca-e66d-4055-9335-8b5560a9200b"),
                            DirectionId = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            Name = "90004"
                        });
                });

            modelBuilder.Entity("CourseBook.WebApi.Profiles.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AdmissionYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.DirectionDisciplineEntity", b =>
                {
                    b.HasOne("CourseBook.WebApi.Faculties.Entities.DirectionEntity", "Direction")
                        .WithMany("Disciplines")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseBook.WebApi.Faculties.Entities.DisciplineEntity", "Discipline")
                        .WithMany("Directions")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.DirectionEntity", b =>
                {
                    b.HasOne("CourseBook.WebApi.Faculties.Entities.FacultyEntity", "Faculty")
                        .WithMany("Directions")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.GroupDisciplineEntity", b =>
                {
                    b.HasOne("CourseBook.WebApi.Faculties.Entities.DisciplineEntity", "Discipline")
                        .WithMany("Groups")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseBook.WebApi.Faculties.Entities.GroupEntity", "Group")
                        .WithMany("Disciplines")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseBook.WebApi.Profiles.Entities.UserEntity", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Discipline");

                    b.Navigation("Group");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.GroupEntity", b =>
                {
                    b.HasOne("CourseBook.WebApi.Faculties.Entities.DirectionEntity", "Direction")
                        .WithMany("Groups")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("CourseBook.WebApi.Profiles.Entities.UserEntity", b =>
                {
                    b.HasOne("CourseBook.WebApi.Faculties.Entities.GroupEntity", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CourseBook.WebApi.Profiles.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseBook.WebApi.Profiles.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CourseBook.WebApi.Profiles.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.DirectionEntity", b =>
                {
                    b.Navigation("Disciplines");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.DisciplineEntity", b =>
                {
                    b.Navigation("Directions");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.FacultyEntity", b =>
                {
                    b.Navigation("Directions");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.GroupEntity", b =>
                {
                    b.Navigation("Disciplines");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
