// <auto-generated />
using System;
using CourseBook.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CourseBook.WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.DirectionDisciplineEntity", b =>
                {
                    b.Property<Guid>("DirectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.HasKey("DirectionId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("directions_disciplines");

                    b.HasData(
                        new
                        {
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            DisciplineId = new Guid("986d7006-65c4-4246-b99a-2d390e1ae4f7")
                        },
                        new
                        {
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            DisciplineId = new Guid("b0a130ae-8d09-4cec-8814-24c811028771")
                        },
                        new
                        {
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            DisciplineId = new Guid("fee99c99-831c-4f29-acd0-5eb5ad0ca7e2")
                        },
                        new
                        {
                            DirectionId = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            DisciplineId = new Guid("d12b6e66-e758-48ca-af31-102aa991bdc0")
                        },
                        new
                        {
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            DisciplineId = new Guid("0142a5ca-e2ab-423a-a03f-d2c3092a0339")
                        },
                        new
                        {
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            DisciplineId = new Guid("09da399f-d269-4333-b3a9-c7203dee1a01")
                        },
                        new
                        {
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            DisciplineId = new Guid("d4e27800-46bd-48d4-b320-92380548f689")
                        },
                        new
                        {
                            DirectionId = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            DisciplineId = new Guid("f333c6ac-530c-4092-8160-a336bafb4d6c")
                        },
                        new
                        {
                            DirectionId = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            DisciplineId = new Guid("8e518999-5273-4789-9978-dac4baa4e74c")
                        },
                        new
                        {
                            DirectionId = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            DisciplineId = new Guid("e1de5ca1-58dd-4a15-8544-0b370db9f2bb")
                        },
                        new
                        {
                            DirectionId = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            DisciplineId = new Guid("f5a8d4f5-a85c-4141-be24-7ba4d2bae6ce")
                        },
                        new
                        {
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            DisciplineId = new Guid("1b773c45-0a73-43f9-94d6-af576c52cf9f")
                        },
                        new
                        {
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            DisciplineId = new Guid("5b63a570-f5b2-47e7-8b2f-a79ca090797a")
                        },
                        new
                        {
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            DisciplineId = new Guid("5687210f-0fe3-4111-b0c6-a4764c3ad27c")
                        },
                        new
                        {
                            DirectionId = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            DisciplineId = new Guid("bc957929-f744-4315-a4ed-08530c7f0f3e")
                        },
                        new
                        {
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            DisciplineId = new Guid("45a4ac18-d257-4bbf-8c90-959c5222aecf")
                        },
                        new
                        {
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            DisciplineId = new Guid("a02c08b7-bd53-43e7-8a83-ead1185fbdd0")
                        },
                        new
                        {
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            DisciplineId = new Guid("db2a6fec-1be3-4e5a-9dc2-71e0104c150d")
                        },
                        new
                        {
                            DirectionId = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            DisciplineId = new Guid("211181c7-ef7c-4de0-b382-70e0eb9c89d3")
                        },
                        new
                        {
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            DisciplineId = new Guid("d6b13c5b-cabf-4034-af31-f3c30d344393")
                        },
                        new
                        {
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            DisciplineId = new Guid("ad97d079-2037-4dd7-abfd-f23befa01df2")
                        },
                        new
                        {
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            DisciplineId = new Guid("d80697b7-aa62-49e2-86e8-2a83e2e71004")
                        },
                        new
                        {
                            DirectionId = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            DisciplineId = new Guid("9fe893d9-19e8-4ca5-99a1-09c165918e8b")
                        },
                        new
                        {
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            DisciplineId = new Guid("bc5bc711-5718-4b9c-a6cf-3d08a00f157c")
                        },
                        new
                        {
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            DisciplineId = new Guid("bf026a3f-9e2a-4506-a411-8bda85002c36")
                        },
                        new
                        {
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            DisciplineId = new Guid("4f4ffe1d-b54c-45f7-9e34-a0cc26df4ddd")
                        },
                        new
                        {
                            DirectionId = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            DisciplineId = new Guid("4bd00c26-498f-439e-b269-5052091dc53f")
                        },
                        new
                        {
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            DisciplineId = new Guid("eeccea9a-ebaa-4660-b2f2-8fad550b38bb")
                        },
                        new
                        {
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            DisciplineId = new Guid("2f9785fd-34f2-47dd-8b5b-e520047213fb")
                        },
                        new
                        {
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            DisciplineId = new Guid("f532bb4b-725b-4b00-8643-a335a4c3fe2f")
                        },
                        new
                        {
                            DirectionId = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            DisciplineId = new Guid("96e8af39-7453-49cb-af5a-28d1e64e001a")
                        },
                        new
                        {
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            DisciplineId = new Guid("0af79477-a80e-4eb6-b156-97bc4cb47315")
                        },
                        new
                        {
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            DisciplineId = new Guid("a5f99e5d-a6a6-4a15-96b0-b2c3f54ce06c")
                        },
                        new
                        {
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            DisciplineId = new Guid("1faf9ce2-d392-4097-af23-2d962b90e9d6")
                        },
                        new
                        {
                            DirectionId = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            DisciplineId = new Guid("ac542825-f958-4103-91ec-89e6363f0d43")
                        },
                        new
                        {
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            DisciplineId = new Guid("7131c3a2-4bc4-4195-859a-f5af9bd7d144")
                        },
                        new
                        {
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            DisciplineId = new Guid("9f160c04-c98b-4d58-a631-cdec4a04e316")
                        },
                        new
                        {
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            DisciplineId = new Guid("fef757f5-8653-4ac3-814d-b60af590ce5a")
                        },
                        new
                        {
                            DirectionId = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            DisciplineId = new Guid("075486bf-0147-4bf7-97ca-e83191675bfb")
                        },
                        new
                        {
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            DisciplineId = new Guid("96cd27bd-dcff-496b-9984-4489b11a2712")
                        },
                        new
                        {
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            DisciplineId = new Guid("b46cc5bc-6fc4-4f1e-9b2a-ff68b3f1234d")
                        },
                        new
                        {
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            DisciplineId = new Guid("3ac05f7b-8ee9-4bf5-a37b-692eb9670c35")
                        },
                        new
                        {
                            DirectionId = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            DisciplineId = new Guid("aad3f967-7158-46ca-9b8a-405581f207a4")
                        },
                        new
                        {
                            DirectionId = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            DisciplineId = new Guid("e55051fc-17a6-41ec-b76e-fe6d98a15058")
                        },
                        new
                        {
                            DirectionId = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            DisciplineId = new Guid("65830d5c-c0b3-46b6-8bea-b3dd2ce6e1dd")
                        },
                        new
                        {
                            DirectionId = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            DisciplineId = new Guid("54f742d3-a89d-4e4a-bd39-d233e0c34395")
                        },
                        new
                        {
                            DirectionId = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            DisciplineId = new Guid("27bedee0-3b3e-4ab2-9bab-7f910ea12df2")
                        },
                        new
                        {
                            DirectionId = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            DisciplineId = new Guid("f3a05565-4293-47b4-8799-78a7e0d8787f")
                        },
                        new
                        {
                            DirectionId = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            DisciplineId = new Guid("abc7d661-c1c4-4bd7-b767-d88ce7b748e5")
                        },
                        new
                        {
                            DirectionId = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            DisciplineId = new Guid("7798ec77-2078-410b-9a47-3ecb1f17b100")
                        },
                        new
                        {
                            DirectionId = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            DisciplineId = new Guid("5f926e12-86e0-4c9f-9f99-734ef39575ca")
                        },
                        new
                        {
                            DirectionId = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            DisciplineId = new Guid("0a89c092-a7df-4570-b7a4-1042d4a08b04")
                        },
                        new
                        {
                            DirectionId = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            DisciplineId = new Guid("579e5d9d-cf33-41d4-a172-56853419f169")
                        },
                        new
                        {
                            DirectionId = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            DisciplineId = new Guid("c43c64b6-d37d-44b6-a6cc-ad890e942b1b")
                        },
                        new
                        {
                            DirectionId = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            DisciplineId = new Guid("ff28aa68-df77-4829-a2ce-f322d4b15a2b")
                        });
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.DirectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("directions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaa504f9-b3ad-4854-9820-90cdcbd27322"),
                            FacultyId = new Guid("6b3957c3-d16e-4620-8d2c-b26239a7a2a8"),
                            Name = "Culturology"
                        },
                        new
                        {
                            Id = new Guid("0efe92d1-4959-4cf5-8969-56bce0e8558c"),
                            FacultyId = new Guid("6b3957c3-d16e-4620-8d2c-b26239a7a2a8"),
                            Name = "Pedagogy"
                        },
                        new
                        {
                            Id = new Guid("9c4684ec-04ab-4da9-9fa2-6ddebb7a5a40"),
                            FacultyId = new Guid("6b3957c3-d16e-4620-8d2c-b26239a7a2a8"),
                            Name = "Design"
                        },
                        new
                        {
                            Id = new Guid("fa2a6596-0f78-42c8-8f3f-56430aa50087"),
                            FacultyId = new Guid("6b3957c3-d16e-4620-8d2c-b26239a7a2a8"),
                            Name = "Library and Information Activities"
                        },
                        new
                        {
                            Id = new Guid("fb92cb9d-c54c-4882-8a84-d357392586b7"),
                            FacultyId = new Guid("e05d5966-b197-4bd1-92d4-800f66b352fe"),
                            Name = "Astronomy and Space Geodesy"
                        },
                        new
                        {
                            Id = new Guid("46c6bba6-91be-4b95-b9c9-812fbdce601e"),
                            FacultyId = new Guid("e05d5966-b197-4bd1-92d4-800f66b352fe"),
                            Name = "Quantum Field Theory"
                        },
                        new
                        {
                            Id = new Guid("d3c7313e-0e11-4f9e-94fe-0b96a66bffa9"),
                            FacultyId = new Guid("e05d5966-b197-4bd1-92d4-800f66b352fe"),
                            Name = "General and Experimental Physics"
                        },
                        new
                        {
                            Id = new Guid("f1db86a1-2647-44ff-81df-6e4781239dcc"),
                            FacultyId = new Guid("e05d5966-b197-4bd1-92d4-800f66b352fe"),
                            Name = "Optics and Spectroscopy"
                        },
                        new
                        {
                            Id = new Guid("435557fa-35a0-4f35-9efa-7aba31755b46"),
                            FacultyId = new Guid("b0d09040-c5ea-492d-936f-488b9f3115a2"),
                            Name = "Radiophysics"
                        },
                        new
                        {
                            Id = new Guid("bc4dd321-36ee-4050-905e-b1aa3fa01182"),
                            FacultyId = new Guid("b0d09040-c5ea-492d-936f-488b9f3115a2"),
                            Name = "Radio electronics"
                        },
                        new
                        {
                            Id = new Guid("ae4d9db2-9358-4a51-9928-888d5338a78e"),
                            FacultyId = new Guid("b0d09040-c5ea-492d-936f-488b9f3115a2"),
                            Name = "Semiconductor Electronics"
                        },
                        new
                        {
                            Id = new Guid("de2a66b0-56ea-44e3-b202-c1b4754b1721"),
                            FacultyId = new Guid("b0d09040-c5ea-492d-936f-488b9f3115a2"),
                            Name = "Optoelectronic systems and remote sensing"
                        },
                        new
                        {
                            Id = new Guid("eb9b5b37-07f2-4e86-a4f0-cc54f186a24a"),
                            FacultyId = new Guid("4a823069-9673-403c-8ea0-59b225e5491c"),
                            Name = "Analytical Chemistry"
                        },
                        new
                        {
                            Id = new Guid("37dd1e11-b958-45ef-ab51-09650b3d43d4"),
                            FacultyId = new Guid("4a823069-9673-403c-8ea0-59b225e5491c"),
                            Name = "Macromolecular compounds"
                        },
                        new
                        {
                            Id = new Guid("afdfcc0a-ffdd-41e1-ab01-a712574e289a"),
                            FacultyId = new Guid("4a823069-9673-403c-8ea0-59b225e5491c"),
                            Name = "Petrochemistry"
                        },
                        new
                        {
                            Id = new Guid("70b17a41-5128-4bde-83dd-f727554ea6b0"),
                            FacultyId = new Guid("4a823069-9673-403c-8ea0-59b225e5491c"),
                            Name = "Physical chemistry"
                        });
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.DisciplineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Literatures")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("disciplines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("986d7006-65c4-4246-b99a-2d390e1ae4f7"),
                            Name = "Art history"
                        },
                        new
                        {
                            Id = new Guid("b0a130ae-8d09-4cec-8814-24c811028771"),
                            Name = "Composition"
                        },
                        new
                        {
                            Id = new Guid("fee99c99-831c-4f29-acd0-5eb5ad0ca7e2"),
                            Name = "Sociology of media"
                        },
                        new
                        {
                            Id = new Guid("d12b6e66-e758-48ca-af31-102aa991bdc0"),
                            Name = "History of material culture"
                        },
                        new
                        {
                            Id = new Guid("0142a5ca-e2ab-423a-a03f-d2c3092a0339"),
                            Name = "Information law"
                        },
                        new
                        {
                            Id = new Guid("09da399f-d269-4333-b3a9-c7203dee1a01"),
                            Name = "Copyright"
                        },
                        new
                        {
                            Id = new Guid("d4e27800-46bd-48d4-b320-92380548f689"),
                            Name = "Quantitative methods in scientific research"
                        },
                        new
                        {
                            Id = new Guid("f333c6ac-530c-4092-8160-a336bafb4d6c"),
                            Name = "Strategic management in the library"
                        },
                        new
                        {
                            Id = new Guid("8e518999-5273-4789-9978-dac4baa4e74c"),
                            Name = "Foreign language"
                        },
                        new
                        {
                            Id = new Guid("e1de5ca1-58dd-4a15-8544-0b370db9f2bb"),
                            Name = "Academic writing"
                        },
                        new
                        {
                            Id = new Guid("f5a8d4f5-a85c-4141-be24-7ba4d2bae6ce"),
                            Name = "Museology, conservation and restoration of historical and cultural objects"
                        },
                        new
                        {
                            Id = new Guid("1b773c45-0a73-43f9-94d6-af576c52cf9f"),
                            Name = "Modern problems of physics of the microworld and cosmology"
                        },
                        new
                        {
                            Id = new Guid("5b63a570-f5b2-47e7-8b2f-a79ca090797a"),
                            Name = "Foreign language in the field of professional communication"
                        },
                        new
                        {
                            Id = new Guid("5687210f-0fe3-4111-b0c6-a4764c3ad27c"),
                            Name = "Waves and layers in plasma"
                        },
                        new
                        {
                            Id = new Guid("bc957929-f744-4315-a4ed-08530c7f0f3e"),
                            Name = "Plasma physics problems"
                        },
                        new
                        {
                            Id = new Guid("45a4ac18-d257-4bbf-8c90-959c5222aecf"),
                            Name = "Military training"
                        },
                        new
                        {
                            Id = new Guid("a02c08b7-bd53-43e7-8a83-ead1185fbdd0"),
                            Name = "Information systems design"
                        },
                        new
                        {
                            Id = new Guid("db2a6fec-1be3-4e5a-9dc2-71e0104c150d"),
                            Name = "Laboratories specializing in satellite dynamics"
                        },
                        new
                        {
                            Id = new Guid("211181c7-ef7c-4de0-b382-70e0eb9c89d3"),
                            Name = "Global Positioning Technologies"
                        },
                        new
                        {
                            Id = new Guid("d6b13c5b-cabf-4034-af31-f3c30d344393"),
                            Name = "Modern problems of physics of the microworld and cosmology"
                        },
                        new
                        {
                            Id = new Guid("ad97d079-2037-4dd7-abfd-f23befa01df2"),
                            Name = "Physics of intermolecular interactions"
                        },
                        new
                        {
                            Id = new Guid("d80697b7-aa62-49e2-86e8-2a83e2e71004"),
                            Name = "The theory of elementary particles"
                        },
                        new
                        {
                            Id = new Guid("9fe893d9-19e8-4ca5-99a1-09c165918e8b"),
                            Name = "Topical issues of theory and teaching methods in physics"
                        },
                        new
                        {
                            Id = new Guid("bc5bc711-5718-4b9c-a6cf-3d08a00f157c"),
                            Name = "Fundamentals of Atomic and Molecular Spectroscopy"
                        },
                        new
                        {
                            Id = new Guid("bf026a3f-9e2a-4506-a411-8bda85002c36"),
                            Name = "Foreign language in the field of professional communication"
                        },
                        new
                        {
                            Id = new Guid("4f4ffe1d-b54c-45f7-9e34-a0cc26df4ddd"),
                            Name = "Analysis of complex biophysical signals"
                        },
                        new
                        {
                            Id = new Guid("4bd00c26-498f-439e-b269-5052091dc53f"),
                            Name = "Biomedical laser technology"
                        },
                        new
                        {
                            Id = new Guid("eeccea9a-ebaa-4660-b2f2-8fad550b38bb"),
                            Name = "Linear Algebra"
                        },
                        new
                        {
                            Id = new Guid("2f9785fd-34f2-47dd-8b5b-e520047213fb"),
                            Name = "Physics"
                        },
                        new
                        {
                            Id = new Guid("f532bb4b-725b-4b00-8643-a335a4c3fe2f"),
                            Name = "Mathematical analysis"
                        },
                        new
                        {
                            Id = new Guid("96e8af39-7453-49cb-af5a-28d1e64e001a"),
                            Name = "Foreign language"
                        },
                        new
                        {
                            Id = new Guid("0af79477-a80e-4eb6-b156-97bc4cb47315"),
                            Name = "Microprocessors"
                        },
                        new
                        {
                            Id = new Guid("a5f99e5d-a6a6-4a15-96b0-b2c3f54ce06c"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("1faf9ce2-d392-4097-af23-2d962b90e9d6"),
                            Name = "Optics Basics"
                        },
                        new
                        {
                            Id = new Guid("ac542825-f958-4103-91ec-89e6363f0d43"),
                            Name = "Military training"
                        },
                        new
                        {
                            Id = new Guid("7131c3a2-4bc4-4195-859a-f5af9bd7d144"),
                            Name = "	Mobile communication systems"
                        },
                        new
                        {
                            Id = new Guid("9f160c04-c98b-4d58-a631-cdec4a04e316"),
                            Name = "Metrology"
                        },
                        new
                        {
                            Id = new Guid("fef757f5-8653-4ac3-814d-b60af590ce5a"),
                            Name = "Digital spectral analysis of signals and fields"
                        },
                        new
                        {
                            Id = new Guid("075486bf-0147-4bf7-97ca-e83191675bfb"),
                            Name = "	Standardization and certification"
                        },
                        new
                        {
                            Id = new Guid("96cd27bd-dcff-496b-9984-4489b11a2712"),
                            Name = "Waveguide Photonics"
                        },
                        new
                        {
                            Id = new Guid("b46cc5bc-6fc4-4f1e-9b2a-ff68b3f1234d"),
                            Name = "Atomic and Nuclear Physics"
                        },
                        new
                        {
                            Id = new Guid("3ac05f7b-8ee9-4bf5-a37b-692eb9670c35"),
                            Name = "Elective disciplines in physical culture and sports"
                        },
                        new
                        {
                            Id = new Guid("aad3f967-7158-46ca-9b8a-405581f207a4"),
                            Name = "Study Practice"
                        },
                        new
                        {
                            Id = new Guid("e55051fc-17a6-41ec-b76e-fe6d98a15058"),
                            Name = "Analytical chemistry"
                        },
                        new
                        {
                            Id = new Guid("65830d5c-c0b3-46b6-8bea-b3dd2ce6e1dd"),
                            Name = "Foreign language"
                        },
                        new
                        {
                            Id = new Guid("54f742d3-a89d-4e4a-bd39-d233e0c34395"),
                            Name = "Quantum chemistry"
                        },
                        new
                        {
                            Id = new Guid("27bedee0-3b3e-4ab2-9bab-7f910ea12df2"),
                            Name = "Pedagogy"
                        },
                        new
                        {
                            Id = new Guid("f3a05565-4293-47b4-8799-78a7e0d8787f"),
                            Name = "Polymer solutions"
                        },
                        new
                        {
                            Id = new Guid("abc7d661-c1c4-4bd7-b767-d88ce7b748e5"),
                            Name = "Chemical modification of polymers"
                        },
                        new
                        {
                            Id = new Guid("7798ec77-2078-410b-9a47-3ecb1f17b100"),
                            Name = "Chemical foundations of biological processes"
                        },
                        new
                        {
                            Id = new Guid("5f926e12-86e0-4c9f-9f99-734ef39575ca"),
                            Name = "Polymer synthesis methods"
                        },
                        new
                        {
                            Id = new Guid("0a89c092-a7df-4570-b7a4-1042d4a08b04"),
                            Name = "Analysis of the quality of hydrocarbon raw materials and products of its processing"
                        },
                        new
                        {
                            Id = new Guid("579e5d9d-cf33-41d4-a172-56853419f169"),
                            Name = "Theoretical foundations of oil refining"
                        },
                        new
                        {
                            Id = new Guid("c43c64b6-d37d-44b6-a6cc-ad890e942b1b"),
                            Name = "Methods for the transmission of scientific information"
                        },
                        new
                        {
                            Id = new Guid("ff28aa68-df77-4829-a2ce-f322d4b15a2b"),
                            Name = "Theoretical foundations of oil refining"
                        });
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.FacultyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("faculties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b3957c3-d16e-4620-8d2c-b26239a7a2a8"),
                            Name = "Institute of Arts and Culture"
                        },
                        new
                        {
                            Id = new Guid("e05d5966-b197-4bd1-92d4-800f66b352fe"),
                            Name = "Faculty of Physics"
                        },
                        new
                        {
                            Id = new Guid("b0d09040-c5ea-492d-936f-488b9f3115a2"),
                            Name = "Faculty of Radiophysics"
                        },
                        new
                        {
                            Id = new Guid("4a823069-9673-403c-8ea0-59b225e5491c"),
                            Name = "Faculty of Chemistry"
                        });
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.GroupDisciplineEntity", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("groups_disciplines");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.GroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DirectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("CourseBook.WebApi.Profiles.Entities.ProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<int>("AdmissionYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.DirectionDisciplineEntity", b =>
                {
                    b.HasOne("CourseBook.WebApi.Faculties.Entities.DirectionEntity", "Direction")
                        .WithMany("Disciplines")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseBook.WebApi.Faculties.Entities.DisciplineEntity", "Discipline")
                        .WithMany("Directions")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.DirectionEntity", b =>
                {
                    b.HasOne("CourseBook.WebApi.Faculties.Entities.FacultyEntity", "Faculty")
                        .WithMany("Directions")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.GroupDisciplineEntity", b =>
                {
                    b.HasOne("CourseBook.WebApi.Faculties.Entities.DisciplineEntity", "Discipline")
                        .WithMany("Groups")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseBook.WebApi.Faculties.Entities.GroupEntity", "Group")
                        .WithMany("Disciplines")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.GroupEntity", b =>
                {
                    b.HasOne("CourseBook.WebApi.Faculties.Entities.DirectionEntity", "Direction")
                        .WithMany("Groups")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.DirectionEntity", b =>
                {
                    b.Navigation("Disciplines");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.DisciplineEntity", b =>
                {
                    b.Navigation("Directions");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.FacultyEntity", b =>
                {
                    b.Navigation("Directions");
                });

            modelBuilder.Entity("CourseBook.WebApi.Faculties.Entities.GroupEntity", b =>
                {
                    b.Navigation("Disciplines");
                });
#pragma warning restore 612, 618
        }
    }
}
